[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82833_xxAA with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --probe 0d28:0204 --chip nRF52833_xxAA"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
